# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        # A directory to store and save the cache
        path: cache
        # An explicit key for restoring and saving the cache
        key: LiveProxyListForClash_cache
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        python ./generate_cfw.py      
    - uses: Shopify/upload-to-release
      with:
        name: my-artifact
        path: temp_config.yml
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        content-type: text/plain # Optional


